name: Health Check

on:
  schedule:
    # Runs at 12:00 UTC (noon) every day
    - cron: "0 12 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fullstackopen-part11-mao6.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
